// <auto-generated />
namespace Licenta_V0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class finalMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202007162222555_finalMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
