//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta_V0.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorAndConfirmMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorAndConfirmMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Licenta_V0.Resources.ErrorAndConfirmMessages", typeof(ErrorAndConfirmMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article was uploaded.
        /// </summary>
        public static string ConfirmArticleUpload {
            get {
                return ResourceManager.GetString("ConfirmArticleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category was deleted..
        /// </summary>
        public static string ConfirmCategoryDeleted {
            get {
                return ResourceManager.GetString("ConfirmCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category was modified..
        /// </summary>
        public static string ConfirmCategoryModify {
            get {
                return ResourceManager.GetString("ConfirmCategoryModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category was added..
        /// </summary>
        public static string ConfirmCategoryUpload {
            get {
                return ResourceManager.GetString("ConfirmCategoryUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article could not be uploaded.
        /// </summary>
        public static string ErrorArticleUpload {
            get {
                return ResourceManager.GetString("ErrorArticleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category could not be modified..
        /// </summary>
        public static string ErrorCatecoryModify {
            get {
                return ResourceManager.GetString("ErrorCatecoryModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category could not be deleted..
        /// </summary>
        public static string ErrorCategoryDeleted {
            get {
                return ResourceManager.GetString("ErrorCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category could not be uploaded..
        /// </summary>
        public static string ErrorCategoryUpload {
            get {
                return ResourceManager.GetString("ErrorCategoryUpload", resourceCulture);
            }
        }
    }
}
