//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta_V0.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Licenta_V0.Resources.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting together the top of the students, Bratianu Scientific Society&apos;s main goal is to bring the new generation closer to science, knowledge and culture. .
        /// </summary>
        public static string Motto {
            get {
                return ResourceManager.GetString("Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once upon a time... this is how classic stories begin, but Bratianu Scientific Society&apos;s story was different, controversial; it had another kind of beginning. Nothing similar to other associations, BSS started from the discussions, fights, dreams and plans of few classmates, colleagues, willing to revolutionize the current system, the way of thinking, the perceptions, maybe even the world. The word spread throughout the College and the number of members rapidly increased, more and more pupils becoming the h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string par1 {
            get {
                return ResourceManager.GetString("par1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how our story began, it went on and it keeps writing itself beautifully everyday. Nothing is impossible -- that is what people say -- and when you truly want something, you succeed. This is what the Society intends: to succeed. What exactly? To promote the idea it believes in: that science is everything but boring, that we are the ones to change something, that waiting does not solve anything and that everything depends on us. We can learn and teach others lots of things and every field can be fasci [rest of string was truncated]&quot;;.
        /// </summary>
        public static string par2 {
            get {
                return ResourceManager.GetString("par2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And... how do we succeed? With a lot of passion, hard work, a strong team behind it, a family in other words, with hope in our future and trust in our hands. With ups and downs, BSS does not stop here, it goes on, fighting agains current injustice. This is who we are: a new generation that thinks independently and build its own path until the end..
        /// </summary>
        public static string par3 {
            get {
                return ResourceManager.GetString("par3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bratianu Scientific Society.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
